[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable Prisma telemetry during build
  CHECKPOINT_DISABLE = "1"
  # Ensure Prisma generates fresh client
  PRISMA_GENERATE_DATAPROXY = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase function timeout for database operations
  timeout = 30

# Redirect all requests to Next.js for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
